name: Auto Release

on:
  schedule:
    - cron: "0 6 1 * *" # 1st of month, 06:00 UTC
  workflow_dispatch:

jobs:
  release:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-auto-release.yaml@c2185213064b9c5089c758c2ae7a5bf4c2339632 # main
    secrets: inherit
