name: Auto Release

on:
  schedule:
    - cron: "0 6 1 * *" # 1st of month, 06:00 UTC
  workflow_dispatch:

jobs:
  release:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-auto-release.yaml@b382020b0709b03c7cd489677137d24a64f98d40 # main
    secrets: inherit
