name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-ci.yaml@81f09fecc7c2077979d1cecb3b83170e334f7136 # main
